version: 1.0.{build}
environment:
  CHOCOAPIKEY:
    secure: cSFEFiqRDJfoyi+T6F3FeZYPRO4V/tOjFHXVTyDdBIGEOm8llQTxoMP487Uqphcf
build_script:
- pwsh: choco pack helloworld.portable/helloworld.portable.nuspec
test: off
artifacts:
- path: '**/helloworld.portable.*.nupkg'
  name: Package
deploy:
- provider: Environment
  name: Chocolatey.org
  on:
    APPVEYOR_REPO_TAG: true
