version: 1.0.{build}
environment:
  CHOCOAPIKEY:
    secure: cSFEFiqRDJfoyi+T6F3FeZYPRO4V/tOjFHXVTyDdBIGEOm8llQTxoMP487Uqphcf
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- pwsh: choco pack helloworld.portable/helloworld.portable.nuspec
test: off
artifacts:
- path: '**/helloworld.portable.*.nupkg'
  name: Package
deploy_script:
- pwsh: >-
    choco apikey --key $CHOCOAPIKEY --source https://push.chocolatey.org/
    choco push
