name: HelloWorld-Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: windows-latest

    steps:
    - name: checkout code
      id:   checkout-code
      uses: actions/checkout@v2

    - name: create choco package
      id:   create-choco-package
      if: success()
      run: choco pack helloworld.portable\helloworld.portable.nuspec
      shell: cmd
